[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[functions."collect-hourly"]
  schedule = "10,25,40,50,54 * * * *"

[functions."collect-on-roster-change"]
  schedule = "*/5 * * * *"
